added simple graphics
deGekata/multitask-empire pull request #4
Opened 2023-04-24 18:57 UTC by deGekata

2023-04-24 19:16 UTC, dainbow commented
Fix naming

2023-04-26 12:06 UTC, dainbow commented on geometry/Line.cpp
> +#include "geometry/Geometry.hpp"
<>

2023-04-26 12:06 UTC, dainbow commented on geometry/Plane.cpp
> +namespace geometry {
Blank line

2023-04-26 12:08 UTC, dainbow commented on include/geometry/GeomVector.hpp
> +#include <geometry/Float.hpp>
Blank line

2023-04-26 12:10 UTC, dainbow commented on include/geometry/Point.hpp
> +#pragma clang diagnostic ignored "-Wconversion"
Ban

2023-04-26 12:51 UTC, XDLoLiK requested changes

2023-04-26 12:51 UTC, XDLoLiK commented on geometry/GeomVector.cpp
> +#include <geometry/geomVector.hpp>
snake case.

2023-04-26 12:51 UTC, XDLoLiK commented on include/graphics/aWindow.hpp
>  namespace igraphicslib {
blank line.

2023-04-26 12:51 UTC, XDLoLiK commented on include/geometry/rect.hpp
>  #pragma clang diagnostic ignored "-Wsign-conversion"
No pragmas. Will leave it for now, but fix in the future.

2023-04-26 15:21 UTC, merged